### ISSUE TITLE
Powerbattery.dll

### ISSUE THREAD

**Issue by Suspycat** [reagcz/IdeapadToolkit#1]
Hello!
Sorry for opening an issue for this, but I did not want to bother you with emails.
I have the exact same model as you, but I run a heavily debloated windows install which would basically require me to reinstall windows to get microsoft store to work again. Would there be a way for you to send me the dll required to run the program?
Thank you in advance, have a nice day!

**Comment by reagcz** [comment]
1.  Go to https://store.rg-adguard.net/
2.  Enter the link to Lenovo Vantage (https://apps.microsoft.com/store/detail/lenovo-vantage/9WZDNCRFJ4MV)
3.  Download the newest version in the .msix format (should be aroud 500 MB). (I honestly don't know if the dll differs between versions. I'll have to verify.)
4. Open the .msix file in 7Zip
5. Inside 7Zip, navigate to LenovoVantagePackage_<version>_x64.msix/DeployAssistant/ImController/Plugins.<date>.cab/plugins.7z/Normal/IdeaNotebookPlugin/x64
6. You should find PowerBattery.dll in there

**Comment by reagcz** [comment]
The method above will work once I fix #2

**Comment by reagcz** [comment]
Turns out some of the dll functions have been changed since I've made this tool. I'll have to make some changes. For the time being, try using the following PowerBattery.dll https://www85.zippyshare.com/v/8ccsyFHH/file.html

**Comment by reagcz** [comment]
The method above will now work for [version 1.1](https://github.com/reagcz/IdeapadToolkit/releases/tag/1.1). I've added updated instructions to the README
