### ISSUE TITLE
Works as *intended* • IdeaPad S145-14IIL (81W6)

### ISSUE THREAD

**Issue by Antonomasia3** [reagcz/IdeapadToolkit#15]
✓ [All] Power Profile
✓ [Conservation, Normal] Battery Charging Mode

TL;DR : this laptop (is *old*, it) doesn't have support for these features,
which is expected to not work in this program too :
• [Rapid] Battery Charging Mode
• [All] Other

.gif (for reference) :
![Animation](https://github.com/reagcz/IdeapadToolkit/assets/89201774/1fad0b49-1b8a-4bdb-b5e1-bb33944afe73)

**Comment by reagcz** [comment]
Thank you for you input

**Comment by Antonomasia3** [comment]
i'm sorry- but the checkbox on README.md is wrong (⁠╥⁠﹏⁠╥⁠)🙏

should be:
✅ Conservation
❌ Rapid
