### ISSUE TITLE
Works on Lenovo Ideapad S340-15API Touch 

### ISSUE THREAD

**Issue by ajayfaul** [reagcz/IdeapadToolkit#23]
Hi, just to make sure that this toolkit, is really works on Lenovo Ideapad S340-15API Touch (81QG)
Detail Specs:
- AMD Ryzen 5 3500u Vega 8
- RAM: 20 GB
- VRAM: 2GB
- SSD: SAMSUNG EVO 970 PLUS 1 TB
- OS Version: Windows 11

Newest Lenovo Vantage on Windows 11 is bringing CPU Throttling and even the SSD what a shame !! it's like they want to break our laptop so we can bought a new one ! it's crazy..

**Comment by chikatambun** [comment]
@ajayfaul Looks like there is OS or Memory limitation on your device, according to this https://psref.lenovo.com/syspool/Sys/PDF/IdeaPad/ideapad_S340_15API/ideapad_S340_15API_Spec.PDF

Hope this tool will work smoothly for you

**Comment by ajayfaul** [comment]
@chikatambun I Finally fix the issue of the throttlhing, it's happen because the GPU settings on the BIOS has some bug, so i just turn OS optimize defaults settings on the BIOS and the throttlhing is gone.
