### ISSUE TITLE
[Feature] French Localization

### ISSUE THREAD

**Issue by mooms06** [reagcz/IdeapadToolkit#31]
Thank you for this app, and thanks for updating it for .Net 8.

Can you make the application translatable ?

I've made a mock-up for a French version:

<img width="300" alt="2024-10-14 12_50_06-Ideapad Toolkit-fr" src="https://github.com/user-attachments/assets/2779ad9f-8b8b-411d-a3b9-f52ec96a5343">

<img width="300" alt="2024-10-14 12_49_40-Ideapad Toolkit" src="https://github.com/user-attachments/assets/2423ac05-2cf9-4ac8-96ea-2b69550ccd3e">

Please note that the UAC shield icon is misplaced in the original version, it should be shifted to the right.

<img width="300" alt="2024-10-14 12_50_06-Ideapad Toolkit" src="https://github.com/user-attachments/assets/438c0af2-9117-419e-af01-39d00d2da079">

**Comment by mooms06** [comment]
I've made a fork with nearly all the changes I wanted.
I was even able to male a release !

https://github.com/mooms06/IdeapadToolkit/releases

**Comment by mooms06** [comment]
Some captures:

![JbRxO4F](https://github.com/user-attachments/assets/534fc0f4-beef-4bc8-b353-c34de524c5e4) 
![hs39vwE](https://github.com/user-attachments/assets/111edd07-a145-426b-b09c-414270e15c2a)
![0NDoT4I](https://github.com/user-attachments/assets/3dbda76f-67da-411a-9aaf-2b5065bf9df0)

**Comment by reagcz** [comment]
I've added proper localization in the newest update. I used the translations from your fork. Thanks. Don't forget to restart the app after changing the language.

**Comment by mooms06** [comment]
That was quick, thanks !

One little mistake: `Home` should be translated to `Accueil` and not `Maison`.

**Comment by reagcz** [comment]
I've fixed it and recreated the release

**Comment by mooms06** [comment]
That's perfect, thank you again.
