### ISSUE TITLE
Large memory footprint - option to NOT stay resident?

### ISSUE THREAD

**Issue by TheDannemand** [reagcz/IdeapadToolkit#33]
Thank you very much for this useful toolkit.

Up until now, I'd been using [Lenovo Legion Toolkit](https://github.com/U-C-S/LegionToolkit) with my Yoga 7 16IRL8. That toolkit has a ton of features, including some very elegant ones, but most of which do not work on my Yoga anyway -- and the features I REALLY need are not compatible with my Yoga.

IdeapadToolkit has JUST those features I need the most, which are to control Power Profile and Battery Charging Mode.

As far as I can tell, it is fully compatible with my Yoga. So again, thank you very much!

One concern I have is memory footprint: IdeapadToolkit stays resident when you close it and consumes a whopping 190MB. I am guessing we have .NET to thank for that.

I need every MB on my 16GB laptop, and while I appreciate the convenience of the Tray icon, I don't need it at all.

Would it be possibly to make staying resident on close an option (similar to Run On Startup)?

Thank you in advance.

**Comment by reagcz** [comment]
Hi, are you sure it's consuming 190MB? Mine consumes just 40MB when running in the taskbar. Are you sure you're looking at the active private working set?

**Comment by reagcz** [comment]
I've added it in the new release. Still, I'd love to see a memory dump of the app running on your system, to see if there's any deeper problems.

**Comment by TheDannemand** [comment]
I cannot believe how quickly you responded and acted. That's amazing!

I should have included TaskManager screendumps in the first place. See attached: One is with the app Open, the other with it in the Tray. Sometimes I see it dropping to ~120MB.

![IdeapadToolkit 1 3 1 - Tray - TaskManager - 2024-11-01](https://github.com/user-attachments/assets/0961cb0e-68ad-47e8-9f2d-061bd612bcdd)

![IdeapadToolkit 1 3 1 - Open - TaskManager - 2024-11-01](https://github.com/user-attachments/assets/b222feb4-ff84-4075-a01b-6d9f82f6f76d)

The new version 1.3.2 works like a charm. Same memory footprint, but not a problem for me, as I close it right away.

Thank you, again, for this excellent tool and for your fast response!

**Comment by reagcz** [comment]
No problem. If you have the time, please upload a memory dump somewhere so I can take a look. There might be a memory leak. However, no one else reported anything like this, so I'll close the issue now.

**Comment by reagcz** [comment]
I could perhaps reduce the memory by switching back to .net framework, or winui 3 with nativeaot, but both would be quite a drag

**Comment by TheDannemand** [comment]
I wouldn't sweat it if I am the only one reporting the high footprint. But naturally I am happy to provide anything you need. What kind of memory dump, and how do I create it?

**Comment by TheDannemand** [comment]
Of course, duh. I just never used that memory dump feature in Task Manager before.

It is uploading to my Google Drive now. I have to attend a meeting and will send you the link in about an hour. Can I share this just with you, not publicly?

**Comment by reagcz** [comment]
Sure, just send it to me via email

**Comment by TheDannemand** [comment]
Sharing it by email (as I am doing here) will still share the link, since
it's a GitHub email address. It's OK, just let me know when you have
downloaded it, and I'll remove the file.

https://drive.google.com/file/d/1HzRNGiDuJFE1swE_At3go1eo8ehfUwQf/view?usp=drive_link

**Comment by TheDannemand** [comment]
I replied by email with link to the memory dump. I then deleted that comment in here after an hour. The email with the link should still be in your Inbox. Otherwise let me know, and I'll share again.

I really am very grateful for your work. If there is anything else I can do, let me know.

**Comment by reagcz** [comment]
It is, I'll get home in a few minutes and download it.

**Comment by reagcz** [comment]
I have downloaded it. You can remove it now. I'll look at it when I have
some time. Thank you so much for sending it to me.

**Comment by reagcz** [comment]
If you're interested, I've analyzed the dump and found no evidence of a memory leak. 
The managed heap takes about 20MB and 30 is used by the unmanaged heap. The rest is taken by all the .NET dlls. 
If the main window is closed and the program is running in the background, most of this memory can get paged to the disk and the active working set goes as low as single digit MBs, so I don't consider the memory usage an issue for now.

**Comment by TheDannemand** [comment]
Thank you, Filip. I am definitely interested and appreciate your report.

Glad to hear memory leaks weren't to blame. So .NET was indeed the culprit, as expected. Still puzzling why it consumes so much more memory on my laptop, but I guess that's the thing with .NET.

I understand what you are saying that most of that memory would likely be paged. Knowing that, I may occasionally leave IdeapadToolkit running in the Tray. But I have it on a HotKey already, so opening it is already as fast and convenient as locating with the mouse in the Tray.

If you are interested in feature ideas for future development (and ONLY if you are) I can suggest a few inspired by Lenovo Legion Toolkit (LLT). 

* Showing battery charge/discharge rate, capacity, charge cycles and other battery info (LLT **Battery** tab).

* Disabling/enabling Vantage (LLT **Settings** tab: toggles tasks in **Task Scheduler Library/Lenovo/Vantage** and **Task Scheduler Library/Lenovo/UDC**, require manual restart after disabling). This allows leaving Vantage installed but disabled, so that one can load it occasionally to install driver updates.

* The requirement to install .NET 8 is one that almost kept me from trying IdeadpadToolkit in the first place. I imagine some others may feel the same.

But seriously, ONLY listen to these if you are interested and looking to expand the software. As it is now, IdeapadToolkit is almost perfect for my use.

Thank you once again for your great work!

**Comment by reagcz** [comment]
Thanks for the ideas. I'll look into them if I have some free time in the future. The .NET 8 runtime... I have three options
a) Switch back to .NET Framework, which is shipped with Windows.
b) Ship the app with an installer, that would install .NET for you, but that felt pretty overkill for such a small app.
c) Publish the app as self-contained, which would pack the runtime with the app, but that increases the exe size to almost 200MB

**Comment by TheDannemand** [comment]
Thank you for explaining. I can definitely understand why you chose what you did, given that it is such a small app.

I think the most appealing of those options from a user standpoint would be (a) since almost everybody has .NET installed with Windows nowadays. It's not like the old days when installing .NET was an extra installation. However .NET 8, however, IS an extra install.

That's just my opinion. Again, I love IdeapadToolkit the way it is already.

**Comment by reagcz** [comment]
As a bit of an experiment, I've ported the app to Windows App Sdk and it is now compiled ahead of time. There is no dependency on the .NET runtime now, so no need to install anything. Hopefully, the memory consumption of this version is a bit better. Note that it's still a bit buggy.

**Comment by TheDannemand** [comment]
Boy, you are unstoppable, Filip!

I just checked now, and see the experimental release, but no binary download yet. I'll test this whenever you feel it is ready for testing. Just say the word.

**Comment by TheDannemand** [comment]
I am sorry to re-open this issue, but I just want to mention that Ideapad Toolkit has worked flawlessly on my Yoga 7 16IRL8 since our exchange in early November. I'd say you can safely add Yoga 7 (possibly other Yogas too) to the list of supported models.

Thanks again for this excellent tool.

**Comment by sahidhh** [comment]
Saw this thread on the resident-memory ask. I ended up writing a small-scope alternative that only does charge mode + Fn+Q power mode (fewer features, not lower RAM — ~110-150 MB, it's a PowerShell tray script): no .NET runtime install, no admin rights, no Vantage needed. MIT licensed.

https://github.com/sahidhh/lenovo-battery-tray

Only tested so far on my own machine (IdeaPad Slim 9 14ITL5 / 82D2) — other IdeaPad/Yoga/Slim models should work in theory (same ACPI\VPC2004 driver) but I can't confirm without more hardware. If anyone here runs it on a different model, a `diag` paste in an issue would help a lot.
