### ISSUE TITLE
Power Profiles not switching

### ISSUE THREAD

**Issue by mikaisfake** [reagcz/IdeapadToolkit#7]
Hi, on the latest version of the app power profiles seem not to be switching for me, everything else seems to toggle just fine.
I have tried using PowerBattery.dll from both latest vantage and the one linked in the other closed issue.

Windows 11 22H2
VSC++Redist 2015-2022 installed
Flex 5 (14ALC05)

![AsiorhKVOS](https://user-images.githubusercontent.com/67816266/202784380-94926b41-87c9-4af1-be3f-4a4d7c9133c3.gif)

**Comment by reagcz** [comment]
If you open Device Manager, can you see these devices in the "System devices" section?
![image](https://user-images.githubusercontent.com/62750643/202787579-7a6db623-4901-408a-8eb6-4507b6105c49.png)

**Comment by reagcz** [comment]
Also, try checking if the ITS Service is running in the Task Manager -> Services tab. 
![image](https://user-images.githubusercontent.com/62750643/202789455-45fb387b-e60e-47e0-9671-65beb60a4064.png)

**Comment by mikaisfake** [comment]
Hi,
The ITS service was stopped, which after enabling solved the issue.
Thanks once again.
