### ISSUE TITLE
Option to change charging behaviour from tray icon instead of performance plan

### ISSUE THREAD

**Issue by Vitamoon** [reagcz/IdeapadToolkit#9]
Would really appreciate if there was a toggle for this. I use the charge settings much more often.

Also, I know it's not in the scope of the project but if there was a way to add a script which turns off the keyboard backlight on boot along with the toolkit autostart I would be very happy.

**Comment by reagcz** [comment]
Hi, I added the option to change the charging mode from the tray icon in the newest release. I'll look into the backlight thing later
